import "./globals.css";
import Header from "../components/Header";
import Providers from "./Providers";

export const metadata = {
  title: "Movie Mania",
  description: "Generated by mr-smoke",
  icons: "/logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
