export const metadata = {
  title: "Movie App",
  description: "Generated by mr-smoke",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
